<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.dataplatform</groupId>
    <artifactId>data-platform-service</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>events-simulator</module>
        <module>events-processor</module>
        <module>infrastructure</module>
        <module>serverless</module>
    </modules>

    <properties>
        <jdk.version>21</jdk.version>
        <release.version>21</release.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <maven-compiler-plugin.version>3.14.0</maven-compiler-plugin.version>
        <maven-dependency-plugin.version>3.10.0</maven-dependency-plugin.version>
        <maven-assembly-plugin.version>3.8.0</maven-assembly-plugin.version>

        <micronaut.version>4.10.13</micronaut.version>
        <micronaut.aot.enabled>false</micronaut.aot.enabled>
        <micronaut.runtime>netty</micronaut.runtime>
        <micronaut.serialization.version>2.16.2</micronaut.serialization.version>
        <micronaut-http-validation.version>4.10.21</micronaut-http-validation.version>

        <awssdk.verion>2.44.0</awssdk.verion>
        <aws-lambda-java-core.version>1.2.3</aws-lambda-java-core.version>
        <iceberg-core.version>1.10.1</iceberg-core.version>
        <hadoop.version>3.4.1</hadoop.version>
        <commons-collections4.version>4.5.0</commons-collections4.version>
        <commons-lang3.version>3.20.0</commons-lang3.version>
        <parquet-column.version>1.16.0</parquet-column.version>
        <lombok.version>1.18.36</lombok.version>
        <logback-classic.version>1.5.32</logback-classic.version>
        <ulid-creator.version>5.2.4</ulid-creator.version>
        <jackson-jsr310.version>2.21.2</jackson-jsr310.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

     <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>io.micronaut.maven</groupId>
                    <artifactId>micronaut-maven-plugin</artifactId>
                    <version>4.11.6</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>3.6.2</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>