kafka:
  enabled: true
  bootstrap:
    servers: "localhost:9092"

  streams:
    default:
      application.id: "dp-data-process-app"
      max.poll.records: 1
      state.dir: "/home/tom/Downloads/tmpdata/statedir"

app:
  platform:
    data:
      catalogDir: "/home/tom/projects/javaworkspace/data-platform-service/catalog-data"
      assumeRoleArn: "arn:aws:iam::128779316957:role/dp-glue-catalog-role-dev"
      region: "ap-southeast-2"
      maxBufferRecords: 1000
      maxBufferTime: "PT2M"
      preCommitMergeWindow: "PT3M"
