micronaut:
  application:
    name: event-processor
  server:
    port: 8082

kafka:
  enabled: true
  bootstrap:
    servers: "${KAFKA_BROKERS}"
  reconnect.backoff.max.ms: 1000
  reconnect.backoff.ms: 50
  retry.backoff.max.ms: 1000
  retry.backoff.ms: 100

  consumers:
    default:
      auto.commit.interval.ms: 100

  executors:
    consumer:
      default:
        allow.auto.create.topics: false
      type: fixed
      nThreads: 10

  streams:
    default:
      application.id: "${STREAM_APP_NAME:dp-data-process-app}"
      processing.guarantee: "exactly_once_v2"
      commit.interval.ms: 100
      producer.transaction.timeout.ms: 60000
      session.timeout.ms: 45000
      heartbeat.interval.ms: 3000
      num.stream.threads: 1
      max.poll.records: ${MAX_POLL_RECORDS}
      auto.offset.reset: "earliest"
      state.dir: "${STREAM_STATE_DIR}"

app:
  platform:
    data:
      catalogDir: "${CATALOG_DATA_DIR}"
      maxBufferRecords: "${MAX_BUFFER_RECORDS}"
      maxBufferTime: "${MAX_BUFFER_TIME}"
      preCommitMergeWindow: "${PRE_COMMIT_MERGE_WINDOW}"
      assumeRoleArn: "${GLUE_ASSUME_ROLE_ARN}"
      region: "${GLUE_AWS_REGION}"
